[versions]
# libraries
junit = "4.13.2"
opentest4j = "1.3.0"
jacksons = "2.17.2"
zxing = "3.5.3"
thumbnailator = "0.4.20"
hutool = "5.8.32"
okhttps = "5.0.0-alpha.14"
jjwts = "0.12.5"

# plugins
intelliJPlatform = "2.5.0"
kotlin = "2.1.20"
changelog = "2.2.1"
qodana = "2024.3.4"
kover = "0.9.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

# jackson
libraries-jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jacksons" }
libraries-jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jacksons" }
libraries-jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jacksons" }
# jackson dataformat
libraries-jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jacksons" }
libraries-jackson-dataformat-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jacksons" }
libraries-jackson-dataformat-properties = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-properties", version.ref = "jacksons" }
libraries-jackson-dataformat-csv = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-csv", version.ref = "jacksons" }
libraries-jackson-dataformat-toml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-toml", version.ref = "jacksons" }
# jackson datatype
libraries-jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jacksons" }

# okhttp
libraries-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttps" }

# JWT
libraries-jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwts" }
libraries-jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwts" }
libraries-jjwt-jackson = { group = "io.jsonwebtoken", name = "jjwt-jackson", version.ref = "jjwts" }

# zxing
libraries-zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
libraries-zxing-javase = { group = "com.google.zxing", name = "javase", version.ref = "zxing" }

# net.coobird:thumbnailator
libraries-thumbnailator = { group = "net.coobird", name = "thumbnailator", version.ref = "thumbnailator" }

# sm crypto
libraries-hutool-crypto = { group = "cn.hutool", name = "hutool-crypto", version.ref = "hutool" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
